---
title: "Qui sont les stagiaires de la formation R ?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
params: 
  gdoc: "https://docs.google.com/spreadsheets/d/1rS5h30nqhk0GS3WLUxBD0jY0u3-Qzm7YC8IpflcAptU/edit?usp=sharing"
---


```{r acquire_data}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("googlesheets",
               "dplyr",
               "flexdashboard",
               "ggplot2",
               "ggmap",
               "sp",
               "hrbrthemes",
               "leaflet",
               "banR",
               "sf")

# lecture des réponses

answers <- gs_url(params$gdoc, lookup = TRUE)

df <- answers %>% 
  gs_read()

```



Column
-----------------------------------------------------------------------

### répondants {.value-box}

```{r}
valueBox(nrow(df), icon = "ion-person-stalker")

```


### Proportion de femmes

```{r}

taux <- sum(df$`Vous êtes` == "Une femme", na.rm = TRUE) / nrow(df) * 100
gauge(round(taux), 0, 100, symbol = "%", sectors = gaugeSectors(success = c(50,100), warning = c(0, 49)))

```

### Âge

```{r}
ggplot(df, aes(x = `Vous avez :`)) +
  geom_bar(fill = "#63A2E7") +
  ylab("") +
  theme_ipsum(grid = "Y", axis_title_just = "l")

```

Column
-----------------------------------------------------------

### Ville de résidence

```{r}
df <- df %>% 
  mutate(adresse = `Indiquez votre ville de provenance`) %>% 
  geocode_tbl(adresse) %>% 
  st_as_sf(coords = c("longitude", "latitude"), dim ="XY", crs = 4326) 
  
df %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addMarkers(clusterOptions = markerClusterOptions())

```

